/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace VaultPay {
  export type PaymentStruct = {
    payer: AddressLike;
    recipient: AddressLike;
    amount: BigNumberish;
    deadline: BigNumberish;
    claimed: boolean;
    cancelled: boolean;
  };

  export type PaymentStructOutput = [
    payer: string,
    recipient: string,
    amount: bigint,
    deadline: bigint,
    claimed: boolean,
    cancelled: boolean
  ] & {
    payer: string;
    recipient: string;
    amount: bigint;
    deadline: bigint;
    claimed: boolean;
    cancelled: boolean;
  };
}

export interface VaultPayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelPayment"
      | "claimPayment"
      | "createPayment"
      | "getPayment"
      | "paymentCount"
      | "payments"
      | "token"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PaymentCancelled"
      | "PaymentClaimed"
      | "PaymentCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPayment",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "payments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "cancelPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
}

export namespace PaymentCancelledEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentClaimedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    payer: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    payer: string,
    recipient: string,
    amount: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    id: bigint;
    payer: string;
    recipient: string;
    amount: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VaultPay extends BaseContract {
  connect(runner?: ContractRunner | null): VaultPay;
  waitForDeployment(): Promise<this>;

  interface: VaultPayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelPayment: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  claimPayment: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  createPayment: TypedContractMethod<
    [_recipient: AddressLike, _amount: BigNumberish, _deadline: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getPayment: TypedContractMethod<
    [_id: BigNumberish],
    [VaultPay.PaymentStructOutput],
    "view"
  >;

  paymentCount: TypedContractMethod<[], [bigint], "view">;

  payments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        payer: string;
        recipient: string;
        amount: bigint;
        deadline: bigint;
        claimed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  token: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelPayment"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimPayment"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createPayment"
  ): TypedContractMethod<
    [_recipient: AddressLike, _amount: BigNumberish, _deadline: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [VaultPay.PaymentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "paymentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "payments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        payer: string;
        recipient: string;
        amount: bigint;
        deadline: bigint;
        claimed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "PaymentCancelled"
  ): TypedContractEvent<
    PaymentCancelledEvent.InputTuple,
    PaymentCancelledEvent.OutputTuple,
    PaymentCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PaymentClaimed"
  ): TypedContractEvent<
    PaymentClaimedEvent.InputTuple,
    PaymentClaimedEvent.OutputTuple,
    PaymentClaimedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentCreated"
  ): TypedContractEvent<
    PaymentCreatedEvent.InputTuple,
    PaymentCreatedEvent.OutputTuple,
    PaymentCreatedEvent.OutputObject
  >;

  filters: {
    "PaymentCancelled(uint256)": TypedContractEvent<
      PaymentCancelledEvent.InputTuple,
      PaymentCancelledEvent.OutputTuple,
      PaymentCancelledEvent.OutputObject
    >;
    PaymentCancelled: TypedContractEvent<
      PaymentCancelledEvent.InputTuple,
      PaymentCancelledEvent.OutputTuple,
      PaymentCancelledEvent.OutputObject
    >;

    "PaymentClaimed(uint256)": TypedContractEvent<
      PaymentClaimedEvent.InputTuple,
      PaymentClaimedEvent.OutputTuple,
      PaymentClaimedEvent.OutputObject
    >;
    PaymentClaimed: TypedContractEvent<
      PaymentClaimedEvent.InputTuple,
      PaymentClaimedEvent.OutputTuple,
      PaymentClaimedEvent.OutputObject
    >;

    "PaymentCreated(uint256,address,address,uint256,uint256)": TypedContractEvent<
      PaymentCreatedEvent.InputTuple,
      PaymentCreatedEvent.OutputTuple,
      PaymentCreatedEvent.OutputObject
    >;
    PaymentCreated: TypedContractEvent<
      PaymentCreatedEvent.InputTuple,
      PaymentCreatedEvent.OutputTuple,
      PaymentCreatedEvent.OutputObject
    >;
  };
}
